SELECT MEMBER_NO, MEMBER_ID, MEMBER_NM, 
TO_CHAR(ENROLL_DT, 'YYYY"년" MM"월" DD"일" HH24MISS')
FROM MEMBER
WHERE MEMBER_ID = user01
AND MEMBER_PW = pass01
AND UNREGISTER_FL = 'N';

SELECT MEMBER_NO, MEMBER_ID, MEMBER_NM,
TO_CHAR(ENROLL_DT, 'YYYY"년" MM"월" DD"일" HH24-MI-SS') ENROLL_DT
FROM MEMBER
WHERE MEMBER_ID = 'user01'
AND MEMBER_PW = 'pass01'
AND UNREGISTER_FL = 'N';

SELECT MEMBER_NO, MEMBER_ID, MEMBER_NM, 
TO_CHAR(ENROLL_DT, 'YYYY"년" MM"월" DD"일" HH24-MI-SS') ENROLL_DT
FROM "MEMBER"
WHERE MEMBER_ID = ?
AND MEMBER_PW = ?
AND UNREGISTER_FL = 'N';


SELECT * FROM MEMBER;

SELECT MEMBER_ID, MEMBER_NM, MEMBER_GENDER
FROM MEMBER;


SELECT MEMBER_ID, MEMBER_NM, DECODE(MEMBER_GENDER, 'M', '남', '여') 성별
FROM "MEMBER"
WHERE UNREGISTER_FL = 'N'
ORDER BY MEMBER_NO DESC;

SELECT COUNT(*) 개수
FROM "MEMBER"
WHERE UNREGISTER_FL = 'N'
AND MEMBER_ID = 'user00';


INSERT INTO MEMBER VALUES (
5, 'user111','pass111','김종조','M',DEFAULT,DEFAULT
);

COMMIT;

UPDATE "MEMBER" SET
MEMBER_PW = 'rlawhdwh'
WHERE MEMBER_ID = 'user111';





-- 게시글 목록조회

SELECT * FROM BOARD;


SELECT BOARD_NO, BOARD_TITLE, MEMBER_NM, CREATE_DT, READ_COUNT, 
		(SELECT COUNT(*) FROM "COMMENT" SUB
		WHERE SUB.BOARD_NO = MAIN.BOARD_NO
		AND DELETE_FL = 'N') COMMENT_COUNT
FROM "BOARD" MAIN
JOIN "MEMBER" USING(MEMBER_NO)
WHERE DELETE_FL = 'N'
ORDER BY BOARD_NO DESC;



SELECT BOARD_NO, BOARD_TITLE, BOARD_CONTENT, MEMBER_NO,
MEMBER_NM, READ_COUNT, CREATE_DT
FROM "BOARD"
JOIN "MEMBER" USING(MEMBER_NO)
WHERE DELETE_FL = 'N'
AND BOARD_NO = 1;



-- 댓글 목록 조회

SELECT * FROM "COMMENT";


SELECT COMMENT_NO, COMMENT_CONTENT, MEMBER_NO, MEMBER_NM, CREATE_DT
FROM "COMMENT"
JOIN "MEMBER" USING(MEMBER_NO)
WHERE DELETE_FL = 'N'
AND BOARD_NO = 1
ORDER BY COMMENT_NO;



CREATE TABLE MEMBER2 AS SELECT * FROM MEMBER;

SELECT * FROM MEMBER2;


