SELECT MEMBER_NO, MEMBER_ID, MEMBER_NM, 
TO_CHAR(ENROLL_DT, 'YYYY"년" MM"월" DD"일" HH24MISS')
FROM MEMBER
WHERE MEMBER_ID = user01
AND MEMBER_PW = pass01
AND UNREGISTER_FL = 'N';

SELECT MEMBER_NO, MEMBER_ID, MEMBER_NM,
TO_CHAR(ENROLL_DT, 'YYYY"년" MM"월" DD"일" HH24-MI-SS') ENROLL_DT
FROM MEMBER
WHERE MEMBER_ID = 'user01'
AND MEMBER_PW = 'pass01'
AND UNREGISTER_FL = 'N';

SELECT MEMBER_NO, MEMBER_ID, MEMBER_NM, 
TO_CHAR(ENROLL_DT, 'YYYY"년" MM"월" DD"일" HH24-MI-SS') ENROLL_DT
FROM "MEMBER"
WHERE MEMBER_ID = ?
AND MEMBER_PW = ?
AND UNREGISTER_FL = 'N';


SELECT * FROM MEMBER;

SELECT MEMBER_ID, MEMBER_NM, MEMBER_GENDER
FROM MEMBER;


SELECT MEMBER_ID, MEMBER_NM, DECODE(MEMBER_GENDER, 'M', '남', '여') 성별
FROM "MEMBER"
WHERE UNREGISTER_FL = 'N'
ORDER BY MEMBER_NO DESC;

SELECT COUNT(*) 개수
FROM "MEMBER"
WHERE UNREGISTER_FL = 'N'
AND MEMBER_ID = 'user00';


INSERT INTO MEMBER VALUES (
5, 'user111','pass111','김종조','M',DEFAULT,DEFAULT
);
