CREATE TABLE EMPLOYEE_COPY AS SELECT * FROM EMPLOYEE;

CREATE TABLE DEPARTMENT_COPY AS SELECT * FROM DEPARTMENT;

CREATE TABLE JOB_COPY AS SELECT * FROM JOB;



SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE_COPY
LEFT JOIN DEPARTMENT_COPY ON (DEPT_CODE = DEPT_ID)
FULL JOIN JOB_COPY USING(JOB_CODE);